branch-defaults:
  feature/checkalarm:
    environment: Mediready-env
environment-defaults:
  Mediready-env:
    branch: null
    repository: null
global:
  application_name: medi-ready
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
